FEKDMETAK2/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FEKDMETAK.Data;
using FEKDMETAK2.Models;
using Microsoft.AspNetCore.Authorization;

namespace FEKDMETAK2.Controllers
{
   
    public class CityController : Controller
    {
        private readonly mvcdbcontext _context;

        public CityController(mvcdbcontext context)
        {
            _context = context;
        }
        [Authorize(Roles = "Admin")]

        // GET: City
        public async Task<IActionResult> Index()
        {
              return _context.Cities != null ? 
                          View(await _context.Cities.ToListAsync()) :
                          Problem("Entity set 'mvcdbcontext.Cities'  is null.");
        }

        // GET: City/Details/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cities == null)
            {
                return NotFound();
            }

            var city = await _context.Cities
                .FirstOrDefaultAsync(m => m.Id == id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // GET: City/Create
        [Authorize(Roles = "Admin")]

        public IActionResult Create()
        {
            return View();
        }

        // POST: City/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] City city)
        {
           
                _context.Add(city);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
           
        }

        // GET: City/Edit/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cities == null)
            {
                return NotFound();
            }

            var city = await _context.Cities.FindAsync(id);
            if (city == null)
            {
                return NotFound();
            }
            return View(city);
        }

        // POST: City/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] City city)
        {
            if (id != city.Id)
            {
                return NotFound();
            }

            
                try
                {
                    _context.Update(city);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CityExists(city.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
           
        }

        // GET: City/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cities == null)
            {
                return NotFound();
            }

            var city = await _context.Cities
                .FirstOrDefaultAsync(m => m.Id == id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // POST: City/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cities == null)
            {
                return Problem("Entity set 'mvcdbcontext.Cities'  is null.");
            }
            var city = await _context.Cities.FindAsync(id);
            if (city != null)
            {
                _context.Cities.Remove(city);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CityExists(int id)
        {
          return (_context.Cities?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

FEKDMETAK2/Controllers/TownController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FEKDMETAK.Data;
using FEKDMETAK2.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace FEKDMETAK2.Controllers
{
    public class TownController : Controller
    {
        private readonly mvcdbcontext _context;

        public TownController(mvcdbcontext context)
        {
            _context = context;
        }

        // GET: Town
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Index()
        {
            var mvcdbcontext = _context.Towns.Include(t => t.City);
            return View(await mvcdbcontext.ToListAsync());
        }

        // GET: Town/Details/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Towns == null)
            {
                return NotFound();
            }

            var town = await _context.Towns
                .Include(t => t.City)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (town == null)
            {
                return NotFound();
            }

            return View(town);
        }

        // GET: Town/Create
        [Authorize(Roles = "Admin")]

        public IActionResult Create()
        {
            //ViewData["CityId"] = new SelectList(_context.Cities, "Id", "Id");
                ViewData["CityId"] = new SelectList(_context.Cities, "Id", "Name"); // Display city names in the dropdown
           
            return View();
        }

        // POST: Town/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,CityId")] Town town)
        {
            
                _context.Add(town);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
            ViewData["CityId"] = new SelectList(_context.Cities, "Id", "Id", town.CityId);
     
        }

        // GET: Town/Edit/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Towns == null)
            {
                return NotFound();
            }

            var town = await _context.Towns.FindAsync(id);
            if (town == null)
            {
                return NotFound();
            }
            ViewData["CityId"] = new SelectList(_context.Cities, "Id", "Id", town.CityId);
            return View(town);
        }

        // POST: Town/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,CityId")] Town town)
        {
            if (id != town.Id)
            {
                return NotFound();
            }
            try
                {
                    _context.Update(town);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TownExists(town.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
           
            ViewData["CityId"] = new SelectList(_context.Cities, "Id", "Id", town.CityId);
            
        }

        // GET: Town/Delete/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Towns == null)
            {
                return NotFound();
            }

            var town = await _context.Towns
                .Include(t => t.City)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (town == null)
            {
                return NotFound();
            }

            return View(town);
        }

        // POST: Town/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Towns == null)
            {
                return Problem("Entity set 'mvcdbcontext.Towns'  is null.");
            }
            var town = await _context.Towns.FindAsync(id);
            if (town != null)
            {
                _context.Towns.Remove(town);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TownExists(int id)
        {
          return (_context.Towns?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

FEKDMETAK2/Controllers/frontController.cs
using FEKDMETAK2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace WebApplication5.Controllers
{
    public class frontController : Controller
    {
        private readonly ILogger<frontController> _logger;

        public frontController(ILogger<frontController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult service()
        {
            return View();
        }
        public IActionResult about()
        {
            return View();
        }
        public IActionResult contact()
        {
            return View();
        }
        public IActionResult team()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }

}

FEKDMETAK2/Views/Shared/Layoutadmin.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>@ViewData["Title"] - My Application</title>
        <!-- Your common meta tags, stylesheets, and scripts -->
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">

        <title>Fe 7dmtak</title>
        <meta content="" name="description">
        <meta content="" name="keywords">

        <!-- Favicons -->
        <link href="assets/img/favicon.png" rel="icon">
        <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-k6RqeWeci5ZR/Lv4MR0sA0FfDOMU6P4rFTO/wu7sfs6pp3B7wzySA5QUR9o23Kf7" crossorigin="anonymous">
        <environment include="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
        </environment>
        <!-- Google Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
        <link href="~/assets/css/main.css" rel="stylesheet" />
        <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/assets/vendor/bootstrap/css/bootstrap.rtl.min.css" rel="stylesheet" />
        <link href="~/assets/vendor/bootstrap/css/bootstrap.rtl.css" rel="stylesheet" />
        <link href="~/assets/vendor/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.min.css" rel="stylesheet" />
        <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />

        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />
        <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" rel="stylesheet" />
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <meta charset="utf-8" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-k6RqeWeci5ZR/Lv4MR0sA0FfDOMU6P4rFTO/wu7sfs6pp3B7wzySA5QUR9o23Kf7" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"]</title>
@*        <link rel="stylesheet" href="~/css/admin.css" />
*@        @RenderSection("Styles", required: false)
    </head>
    <body>

        <!-- ======= Header ======= -->
        <section id="topbar" class="topbar d-flex align-items-center">
            <div class="container d-flex justify-content-center justify-content-md-between">
                <div class="contact-info d-flex align-items-center">
                <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:contact@example.com">Fe 7'dmtak@gmail.com</a></i>
                    <i class="bi bi-phone d-flex align-items-center ms-4"><span>+1 5589 55488 55</span></i>
                </div>
                <div class="social-links d-none d-md-flex align-items-center">
                    <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                    <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                    <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                    <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                </div>
            </div>
        </section> <!-- End Top Bar -->

        <header id="header" class="header d-flex align-items-center">

            <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
                <a href="index.html" class="logo d-flex align-items-center">
                    <h1>Fe 7dmtak<span>.</span></h1>
                </a>
                <nav id="navbar" class="navbar">
                    <ul class="navbar4">
                        <li class="nav-item">
                            <a class="nav-link text-dark4" asp-area="" asp-controller="User" asp-action="Index">الموظفين</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark4" asp-area="" asp-controller="User" asp-action="Index2">السمتخدمين</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark4" asp-area="" asp-controller="Specialization" asp-action="Index">Specializations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark4" asp-area="" asp-controller="City" asp-action="Index">Cities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark4" asp-area="" asp-controller="Town" asp-action="Index">Towns</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark4" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                        </li>
                      @*  @if (!string.IsNullOrEmpty(Context.Session.GetString("email")))
                        {
                            <li class="navbar">
                                <a class="navbar" asp-area="" asp-controller="Home" asp-action="Profile">
                                    <i class="fa-solid fa-user"></i> <!-- Replace this with your desired icon -->
                                </a>
                            </li>
                        }
*@
                    </ul>
                </nav>
                <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
                <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

            </div>
        </header>
    <div>
        @RenderBody()
    </div>
    <footer id="footer" class="footer">

        <div class="container">
            <div class="row gy-4">
                <div class="col-lg-5 col-md-12 footer-info">
                    <a href="index.html" class="logo d-flex align-items-center">
                        <span>Fe 7'dmtak</span>
                    </a>
                    <p> في خدمتك وفرلك كل الخدمات اللي ممكن تحتاجها تقدر تطلبها في اي وقت و اي مكان</p>
                    <div class="social-links d-flex mt-4">

                        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                    </div>
                </div>

                <div class="col-lg-2 col-6 footer-links">
                    <h4>روابطنا</h4>
                    <ul>
                        <li class="navbar">
                            <a class="navbar" asp-area="." asp-controller="front" asp-action="index">الصفحة الرئيسية</a>
                        </li>
                        <li class="navbar">
                            <a class="navbar" asp-area="" asp-controller="front" asp-action="about">عننا</a>
                        </li>
                        <li class="navbar">
                            <a class="navbar" asp-area="" asp-controller="front" asp-action="contact">تواصل معنا</a>
                        </li>
                        <li class="navbar">
                            <a class="navbar" asp-area="" asp-controller="front" asp-action="team">فريق العمل</a>
                        </li>
                        <li class="navbar">
                            <a class="navbar" asp-area="" asp-controller="front" asp-action="service">الخدمات</a>
                        </li>
                        
                    </ul>
                </div>
                <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
                    <h4>تواصل معانا</h4>
                    <strong>Phone:</strong> +1 5589 55488 55<br>
                    <strong>Email:</strong> Fe 7'dmtak13@gmail.com<br>
                    </p>

                </div>

            </div>
        </div>

        <div class="container mt-4">
            <div class="copyright">
                &copy; Copyright <strong><span>Fe 7'dmtak</span></strong>. All Rights Reserved

            </div>

    </footer>

    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    @*<div id="preloader"></div> *@
    @* <div id="preloader"></div> *@

    <!-- Vendor JS Files -->

    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.esm.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.esm.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.esm.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.esm.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FEKDMETAK2/Views/Shared/SetRate.cshtml
@model FEKDMETAK.Models.Review
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fix today</title>
    @*   <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="fontawesome/css/all.min.css">*@
    <link href="~/css/templatemo-style.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/a363edd0e0.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
    <font-awesome-icon :icon="['far', 'arrow-up']" />
    <FontAwesomeIcon icon="fa-duotone fa-arrow-up" />
    <font-awesome-icon :icon="['fad', 'arrow-up']" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>profile</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

</head>
<div>
    <span class="pull-right">
        @for (int i = 0; i < Model.TotalRate; i++)
        {
            <i class="fa fa-star fa-2x text-primary" style="color: gold;"></i>
        }
        @for (int i = 0; i < 5-Model.TotalRate; i++)
        {
            <i class="fa fa-star fa-2x text-muted" style="color: gold;"></i>
        }


       
    </span>
   
</div>

FEKDMETAK2/Views/Shared/_RatingPartialView.cshtml
@{
    var hasReviewed = ViewBag.HasReviewed as bool? ?? false;
    var reviewedUserId = ViewBag.ReviewedUserId as int?;
}

<div class="rating" id="rating">
    <div class="stars" id="stars">
        <span class="star" data-value="1">&#9733;</span>
        <span class="star" data-value="2">&#9733;</span>
        <span class="star" data-value="3">&#9733;</span>
        <span class="star" data-value="4">&#9733;</span>
        <span class="star" data-value="5">&#9733;</span>
    </div>
    <div class="rating-count" id="ratingCount">0</div>
</div>

<style>
    .stars {
        display: flex;
        justify-content: center;
    }

    .star {
        font-size: 24px;
        cursor: pointer;
        color: #ccc;
    }

        .star:hover,
        .star.active {
            color: #ffac42;
        }
</style>