FEKDMETAK2/Models/Specialization.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.Extensions.Configuration.UserSecrets;
namespace FEKDMETAK.Models
{
    public class Specialization
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Sid { set; get; }
        public string SName { set; get; }
        //public User User {  set; get; }
    }
}

FEKDMETAK2/Controllers/NotificationController.cs
using FEKDMETAK.Models;
using Microsoft.AspNetCore.Mvc;
using FEKDMETAK.Data;
using FEKDMETAK2.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Globalization;
using System;
using System.Security.Policy;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using System.Security.Cryptography;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using NuGet.Protocol.Plugins;


namespace FEKDMETAK2.Controllers
{
    public class NotificationController : Controller
    {
        private readonly mvcdbcontext _context;
        public NotificationController(mvcdbcontext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CreateNotification()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateNotification(Notification model)
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> SentNotificationAsync(int id)
        {
            var notifications = await _context.Notifications
.Include(n => n.Sender).Include(n => n.Reciever) // Ensure the Sender information is included
.ToListAsync();
            bool hasUsersOfType = _context.Users.Any(record => record.Type == UserType.موظف && record.Uid == id);
            if (hasUsersOfType)
            {
                var matchingRows = _context.Notifications.Where(record => record.RecieverId == id && record.IsAccepted == false && record.IsRejected == false).ToList();
                // Pass the matchingRows to the view
                //return View(matchingRows);

                int matchingRowsCount = _context.Notifications.Count(record => record.RecieverId == id && !record.IsAccepted && !record.IsRejected);
                TempData["count"] = matchingRowsCount;
                ViewBag.num = 0;
                var profileUrl = GetProfileUrl(id);
                ViewBag.ProfileUrl = profileUrl;
                return View(matchingRows);

            }
            else
            {
                var matchingRows = _context.Notifications.Where(record => record.SenderId == id && (record.IsAccepted == true || record.IsRejected == true)).ToList();
                // Pass the matchingRows to the view
                //return View(matchingRows);

                int matchingRowsCount = _context.Notifications.Count(record => record.SenderId == id && (record.IsAccepted || record.IsRejected));
                TempData["key"] = matchingRowsCount;
                var url = "/Home/Profile?key=" + TempData["count"];
                ViewBag.num = 1;
                return View(matchingRows);

            }
            return View();
        }

        private string GetProfileUrl(int senderId)
        {
            // Logic to generate the profile URL based on the SenderId
            // Replace this with your actual logic
            var user = _context.Users.FirstOrDefault(u => u.Uid == senderId);
            return user != null ? $"/Home/Profile/{senderId}" : string.Empty;
        }
        [HttpPost]
        public IActionResult getvalue(int reviewed)
        {
            TempData["reviewed"] = reviewed;
            return RedirectToAction("SentNotification");
        }
        [HttpPost]

        public IActionResult SentNotification(string message, DateTime date, Clock clock, AmPm amPm)
        {
            int reviewedId = Convert.ToInt32(TempData["reviewed"]);
            var model = new Notification
            {
                Message = message,
                Date = date,
                Clock = clock,
                AmPm = amPm
            };

            User user = new User();
            var senderId = 1;
            //var loggedInUserEmail = User.Identity.Name;
            var loggedInUser = _context.Users.FirstOrDefault(u => u.email == user.email);
            if (loggedInUser != null)
            {
                var UserId = loggedInUser.Uid; // Assuming the user ID property is named "Uid"
                                               // Use userId as needed (e.g., store it in session, pass it to view, etc.)
                HttpContext.Session.SetInt32("userId", UserId);
                senderId = UserId;
                HttpContext.Session.SetInt32("userId", senderId);
                ViewBag.SenderName = $"{loggedInUser.FName} {loggedInUser.LName} {loggedInUser.Photo}";
            }


            bool senderExists = _context.Users.Any(u => u.Uid == senderId);
            // Proceed with saving the Notification object if the sender exists
            if (senderExists)
            {
                Notification notification = new Notification
                {
                    Message = message,
                    Date = date,
                    Clock = clock,
                    AmPm = amPm,
                    SenderId = HttpContext.Session.GetInt32("userId") ?? 0,
                    RecieverId = reviewedId,  // Set the appropriate RecieverId value
                    IsAccepted = false,
                    IsRejected = false
                };
                //var id2 = HttpContext.Session.GetInt32("userId") ?? 0;
                int newNotificationId = notification.NOId;

                _context.Notifications.Add(notification);
                _context.SaveChanges();
                Console.WriteLine("stored successully");             // Handle the case when the sender does not exist

                //TempData["MatchingRows"] = id;
                //RedirectToAction("SentNotification",id);
                //RedirectToAction("Profile","Home", senderId);
                return Ok();
                RedirectToAction("isaccept", newNotificationId);

            }
            else
            {
                Console.WriteLine("cannot store");             // Handle the case when the sender does not exist
                // Return an appropriate error message or redirect the user
            }
            return View(model);
        }
        [HttpPost]
        public IActionResult isaccept([FromBody] JsonElement data, int newNotificationId)
        {
            string action2 = data.GetProperty("action").GetString();
            string notificationId = data.GetProperty("notificationId").GetString();
            int notificationId2 = int.Parse(notificationId);

            var notification = _context.Notifications.FirstOrDefault(n => n.NOId == notificationId2);
            if (notification != null)
            {

                if (action2 == "Accept")
                {
                    notification.IsAccepted = true;
                    notification.IsRejected = false;
                }
                else if (action2 == "Reject")
                {
                    notification.IsAccepted = false;
                    notification.IsRejected = true;
                }
                else
                {
                    // Handle invalid action value
                    return RedirectToAction("OtherAction");
                }

                _context.SaveChanges();
            }

            // Redirect to a different action or return an appropriate view
            return Ok();
        }
        [HttpGet]
        public IActionResult UserRecievedNo()
        {
            //var matchingRows = _context.Notifications.Where(record => record.SenderId == id && (record.IsAccepted == true || record.IsRejected == true)).ToList();

            //int matchingRowsCount = _context.Notifications.Count(record => record.RecieverId == id && !record.IsAccepted && !record.IsRejected);
            //ViewData["count"] = matchingRowsCount;

            // Pass the matchingRows data to the view
            return View();
        }



        //[HttpPost]
        //public IActionResult HandleNotification(string action, string message, DateTime date, Clock clock, AmPm amPm, int SenderId, int ReceiverId, int value)
        //{
        //    try
        //    {
        //        Check if the receiver exists in the Users table
        //        if (!_context.Users.Any(u => u.Uid == ReceiverId))
        //        {
        //            return Json(new { success = false, message = "Receiver does not exist." });
        //        }

        //        Create a new instance of the Notification model and set the values
        //        var notification = new Notification
        //        {
        //            Message = message,
        //            Date = date,
        //            Clock = clock,
        //            AmPm = amPm,
        //            SenderId = HttpContext.Session.GetInt32("userId") ?? 0,
        //            IsAccepted = action == "Accept",
        //            IsRejected = action == "Reject"
        //        };

        //        _context.Add(notification);
        //        _context.SaveChanges();

        //        return Json(new { success = true, message = "Notification saved successfully" });
        //    }
        //    catch (Exception ex)
        //    {
        //        return Json(new { success = false, message = "Error occurred while saving the notification" });
        //    }
        //}






    }
}

FEKDMETAK2/Views/Specialization/Create.cshtml
@model FEKDMETAK.Models.Specialization

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/Layoutadmin.cshtml";
}
<link href="~/css/admin.css" rel="stylesheet" />


<link href="~/css/style.css" rel="stylesheet" />
<h1>Create</h1>

<h4>Specialization</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SName" class="control-label"></label>
                <input asp-for="SName" class="form-control" />
                <span asp-validation-for="SName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FEKDMETAK2/Views/Specialization/Delete.cshtml
@model FEKDMETAK.Models.Specialization

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/Layoutadmin.cshtml";
}
<link href="~/css/admin.css" rel="stylesheet" />
<link href="~/css/delet.css" rel="stylesheet" />

<link href="~/css/style.css" rel="stylesheet" />
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Specialization</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Sid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FEKDMETAK2/Views/Specialization/Details.cshtml
@model FEKDMETAK.Models.Specialization

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/Layoutadmin.cshtml";
}
<link href="~/css/admin.css" rel="stylesheet" />


<link href="~/css/style.css" rel="stylesheet" />

<h1>Details</h1>

<div>
    <h4>Specialization</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Sid">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FEKDMETAK2/Views/Specialization/Edit.cshtml
@model FEKDMETAK.Models.Specialization

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/Layoutadmin.cshtml";
}
<link href="~/css/admin.css" rel="stylesheet" />


<link href="~/css/style.css" rel="stylesheet" />
<h1>Edit</h1>

<h4>Specialization</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Sid" />
            <div class="form-group">
                <label asp-for="SName" class="control-label"></label>
                <input asp-for="SName" class="form-control" />
                <span asp-validation-for="SName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FEKDMETAK2/Views/Specialization/Index.cshtml
@model IEnumerable<FEKDMETAK.Models.Specialization>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/Layoutadmin.cshtml";
}

<link href="~/css/admin.css" rel="stylesheet" />
<link href="~/css/style.css" rel="stylesheet" />
<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Sid">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Sid">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Sid">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

FEKDMETAK2/Views/Specialization/UserProfile.cshtml
@model FEKDMETAK.Models.User
@{
    var hasReviewed = ViewBag.HasReviewed as bool? ?? false;
    var reviewedUserId = ViewBag.ReviewedUserId as int?;
}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fix today</title>
    @*   <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="fontawesome/css/all.min.css">*@
    <link href="~/css/templatemo-style.css" rel="stylesheet" />
    <link href="~/css/userprofile.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/a363edd0e0.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
    <font-awesome-icon :icon="['far', 'arrow-up']" />
    <FontAwesomeIcon icon="fa-duotone fa-arrow-up" />
    <font-awesome-icon :icon="['fad', 'arrow-up']" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>profile</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

</head>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">.     </div>

                <div class="card-body">
                    <div class="user-photo text-center">
                        <img src="data:image/jpeg;base64,@Convert.ToBase64String(Model.Photo)" alt="User Photo" class="rounded-circle" style="width: 150px; height: 150px;">
                    </div>
                    @{
                        var base64 = Convert.ToBase64String(Model.Photo);
                        var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                    }

                    <div class="user-box">
                        <div class="user-details text-center">
                            <h4>@Model.FName @Model.LName</h4>
                            @{
                                var ratingsum = ViewBag.ratingsum;
                                var ratingcount = ViewBag.ratingcount;
                                decimal rating = 0;
                                if (ratingcount > 0)
                                {
                                    rating = (ratingsum / ratingcount);
                                }
                                var totalrate = decimal.Parse(rating.ToString());
                            }
                            @if (ViewBag.check == 1)
                            {

                                <p>your rate is:</p>
                                <span class="pull-right">
                                    @{
                                        if (ViewBag.rate != null)
                                        {
                                            int integerRate = (int)Math.Round(ViewBag.rate);
                                            for (int i = 0; i < integerRate; i++)
                                            {
                                                <i class="fa fa-star fa-2x" style="color: gold;"></i>
                                            }
                                        }
                                    }
                                </span>
                                <p>total rate is:</p>
                                <span class="pull-right">
                                    @{
                                        if (ViewBag.total != null)
                                        {
                                            int Rate = (int)Math.Round(ViewBag.total);
                                            for (int i = 0; i < Rate; i++)
                                            {
                                                <i class="fa fa-star fa-2x" style="color: gold;"></i>

                                            }
                                        }
                                    }
                                </span>
                            }
                            else
                            {
                                <partial name="_RatingPartialView" />
                                <div id="1">
                                </div>
                            }

                            <p>البريد الإلكتروني: @Model.email</p>
                            <p>التخصص: @ViewBag.SpecializationName</p>
                            <p>  المحافظة:@Model.Town.City.Name </p>
                            <p>  المركز:@Model.Town.Name </p>

                            <p>العمر: @Model.age</p>
                            <p>النوع: @Model.Gender</p>
                            <p>العنوان: @Model.Adderess</p>
                            <form asp-controller="Notification" asp-action="CreateNotification" method="post">
                                <input type="hidden" name="SenderId" value="@ViewBag.userId">
                                <input type="hidden" name="ReceiverId" value="@ViewBag.user">
                                <button type="submit" class="btn-success" color="background_color green">حجز موعد</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    @*   @section Scripts {
    *@        <script>

                  document.addEventListener("DOMContentLoaded", function () {
                      const stars = document.querySelectorAll('.star');
                      const ratingCount = document.getElementById('ratingCount');

                      let rating = 0;

                      stars.forEach(star => {
                          star.addEventListener('click', () => {
                              const value = parseInt(star.getAttribute('data-value'));
                              rating = value;
                              updateStars(value);
                              sendRating(value);
                          });
                      });


                      function updateStars(value) {
                          stars.forEach((star, index) => {
                              if (index < value) {
                                  star.classList.add('active');
                              } else {
                                  star.classList.remove('active');
                              }
                          });
                          ratingCount.textContent = value;
                      }
                      function disableStars() {
                          stars.forEach(star => {
                              star.classList.add('disabled');
                              star.style.pointerEvents = 'none';
                          });
                      }

                      function sendRating(value) {
                          // Send rating to the server using AJAX
                          $.ajax({
                              url: '/Specialization/AddReview', // Update with your controller action URL
                              method: 'POST',
                              data: { id: @ViewBag.reviewed, rateOfUser: value },
                              success: function (response) {
                                  // Update the partial view with the new total rating
                                  console.log('Rating submitted: ' + value);
                                  document.getElementById(1).innerHTML = response;

                                  // Disable the stars after successful rating
                                  hasReviewed = true;
                                  disableStars();
                              },
                              error: function (error) {
                                  console.error('Error:', error);
                              }
                          });
                      }

                      updateStars(0);

                  });

    </script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var reviewedValue = '@ViewBag.reviewed';
            $.ajax({
                url: '/Notification/getvalue', // Replace with the correct URL of the other controller's action
                method: 'POST',
                data: { reviewed: reviewedValue },
                success: function (response) {
                    console.log('Value sent successfully');
                    // Handle the success response as needed
                },
                error: function (error) {
                    console.error('Error sending value:', error);
                    // Handle the error response as needed
                }
            });
        });

    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var hasReviewed = @hasReviewed.ToString().ToLower() === 'true';
            var reviewedUserId = @reviewedUserId;

            if (hasReviewed) {
                disableStars();
            }

            function disableStars() {
                var stars = document.querySelectorAll('.star');
                stars.forEach(function (star) {
                    star.style.pointerEvents = 'none';
                    star.style.color = '#ccc';
                });
            }

            document.querySelectorAll('.star').forEach(function (star) {
                star.addEventListener('click', function () {
                    if (!hasReviewed) {
                        var rating = this.getAttribute('data-value');
                        document.getElementById('ratingCount').innerText = rating;
                        document.querySelectorAll('.star').forEach(function (s) {
                            s.classList.remove('active');
                            if (s.getAttribute('data-value') <= rating) {
                                s.classList.add('active');
                            }
                        });

                        // Submit the rating via AJAX
                        fetch('@Url.Action("SubmitReview")', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                'RequestVerificationToken': document.querySelector('input[name="__RequestVerificationToken"]').value
                            },
                            body: JSON.stringify({
                                reviewedUserId: reviewedUserId,
                                rate: rating
                            })
                        }).then(response => response.json())
                            .then(data => {
                                if (data.success) {
                                    hasReviewed = true;
                                    disableStars();
                                } else {
                                    alert(data.message);
                                }
                            });
                    }
                });
            });
        });
    </script>

    <style>
        .stars {
            display: flex;
            justify-content: center;
        }

        .star {
            font-size: 24px;
            cursor: pointer;
            color: #ccc;
        }

            .star:hover,
            .star.active {
                color: #ffac42;
            }

        .user-photo {
            text-align: center;
            margin-bottom: 10px;
        }

            .user-photo img {
                border-radius: 50%;
                width: 100px;
                height: 100px;
            }

        .rating {
            display: inline-block;
        }

            .rating input {
                display: none;
            }

            .rating label {
                float: right;
                color: #aaa;
            }

                .rating label:before {
                    content: "\2605";
                    font-size: 2em;
                }

            .rating input:checked ~ label {
                color: #e1ad01;
            }
    </style>
   

FEKDMETAK2/Views/Specialization/_SpecializationList.cshtml
@model IEnumerable<FEKDMETAK.Models.Specialization>

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-sm-3">
                <div class="specialization-name">
                    <a href="@Url.Action("userbyspe","User" , new{ spe = item.Sid})">
                        <h4>@item.SName</h4>
                    </a>
                </div>
            </div>
        }
    </div>
</div>

FEKDMETAK2/Views/Specialization/specialization.cshtml
@model IEnumerable<FEKDMETAK.Models.Specialization>
<head>
    <link href="~/assets/css/main.css" rel="stylesheet" />
</head>
@*<div class="sections-bg">
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-sm-3">
                <div class="specialization-name">
                    <a href="@Url.Action("userbyspe","User" , new{ spe = item.Sid})">
                        <h4>@item.SName</h4>
                    </a>
                </div>
            </div>
        }
    </div>
</div>
</div>*@


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Specialization Search</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="~/css/templatemo-style.css">
    <script src="https://kit.fontawesome.com/a363edd0e0.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <form class="d-flex tm-search-form" id="searchForm" onsubmit="return false;">
        <input name="Search" id="searchInput" class="form-control tm-search-input" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success tm-search-btn" type="submit">
            <i class="fas fa-search"></i>
        </button>
    </form>
    <div class="sections-bg">
    <br />
    <div class="container">
        <div id="specializationList">
            @Html.Partial("_SpecializationList", Model)
        </div>
    </div>
</body>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        let debounceTimer;
        $('#searchInput').on('input', function () {
            clearTimeout(debounceTimer);
            const searchValue = $(this).val();
            debounceTimer = setTimeout(() => {
                $.ajax({
                    url: '@Url.Action("Specialization")',
                    type: 'GET',
                    data: { Search: searchValue },
                    success: function (result) {
                        $('#specializationList').html(result);
                    }
                });
            }, 300); // Delay of 300ms
        });
    });
</script>
<style>
    .sections-bg {
        background-color: #f6f6f6;
    }

    .col-sm-3{
        margin-top:40px;
    }
    
   
  
    .specialization-name {
      /*  padding: 32px;
       ;
        background-color: #f0f0f0;
        border-radius: 15px;
        box-shadow: 6px 5px 17px rgba(0, 0, 0, 0.2);
        text-align: center;
        margin-bottom: 40px;
        transition: all 0.3s ease;
        width: 200px;
        height:100px;*//* Set the initial width */
        padding: 40px;
        background: #fff;
        height: 100%;
        border-radius: 20px;
     /*   margin-top:50px;*/
/*        margin-bottom:25px;
*/        margin-left:30px;
        text-align: center;
        transition-duration: 0.2s;
        transition-timing-function: ease;
        transition-delay: 0.2s;
/*        border: 1px solid #987e5a;
*/    }

    .form-control {
        margin-top: 20px;
    }
    button:not(:disabled), [type=button]:not(:disabled), [type=reset]:not(:disabled), [type=submit]:not(:disabled) {
        cursor: pointer;
        margin-top: 20px;
    }

        .specialization-name a {
            text-decoration: none;
            color: #333;
            cursor:pointer;
        }

        .specialization-name:hover {
/*            background-color: #e0e0e0;
*/           box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.4);
    
            /* Adjust box shadow on hover */
        }

            .specialization-name:hover a {
                color:#987e5a;
                ; /* Change color of specialization name on hover */
            }


</style>