FEKDMETAK2/Models/Notification.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FEKDMETAK2.Models;
using Microsoft.Extensions.Configuration.UserSecrets;
namespace FEKDMETAK.Models
{
    public enum Clock
    {
        one = 1, two = 2, three = 3, four = 4, five = 5, six = 6, seven = 7, eight = 8,
        nine = 9, ten = 10, eleven = 11, twelve = 12,
    }
    public enum AmPm
    {
        am, pm
    }
    public class Notification
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int NOId { set; get; }
        [Required(ErrorMessage = "The Message field is required.")]
        public string Message { set; get; }
        public bool IsAccepted { set; get; }
        public bool IsRejected { set; get; }
        public int SenderId { set; get; }
        public int RecieverId { set; get; }
        public DateTime Date { set; get; }
        public Clock Clock { set; get; }
        public AmPm AmPm { set; get; }
        public User Sender { set; get; }
        public User Reciever { set; get; }

    }
}

FEKDMETAK2/Controllers/SpecializationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FEKDMETAK.Data;
using FEKDMETAK.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Cryptography;
using System.Xml.Linq;

namespace FEKDMETAK2.Controllers
{
    public class SpecializationController : Controller
    {
        private readonly mvcdbcontext _context;

        public SpecializationController(mvcdbcontext context)
        {
            _context = context;
        }
        private decimal CalculateAverageRateForUser(int userId)
        {
            // Retrieve all reviews where the user is either the reviewer or the reviewed user
            var reviews = _context.Reviews.Where(r => r.ReviewedUserId == userId || r.ReviewerId == userId).ToList();

            // Calculate the total rate
            decimal totalRate = reviews.Sum(r => r.RateofUser);

            // Calculate the average rate
            decimal averageRate = reviews.Count > 0 ? totalRate / reviews.Count : 0;

            return averageRate;
        }

        public async Task<IActionResult> Specialization(string Search)
        {
            if (!String.IsNullOrEmpty(Search))
            {
                var search = await _context.Specializations
                    .Where(n => n.SName.ToLower().Contains(Search.ToLower()))
                    .ToListAsync();

                if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return PartialView("_SpecializationList", search);
                }

                return View(search);
            }
            else
            {
                var specializations = await _context.Specializations.ToListAsync();

                if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return PartialView("_SpecializationList", specializations);
                }

                return View(specializations);
            }
        }

        // GET: Specialization
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Index()
        {
              return _context.Specializations != null ? 
                          View(await _context.Specializations.ToListAsync()) :
                          Problem("Entity set 'mvcdbcontext.Specializations'  is null.");
        }

        // GET: Specialization/Details/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Specializations == null)
            {
                return NotFound();
            }

            var specialization = await _context.Specializations
                .FirstOrDefaultAsync(m => m.Sid == id);
            if (specialization == null)
            {
                return NotFound();
            }

            return View(specialization);
        }

        // GET: Specialization/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Specialization/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Create([Bind("Sid,SName")] Specialization specialization)
        {
                _context.Add(specialization);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
            return View(specialization);
        }

        // GET: Specialization/Edit/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Specializations == null)
            {
                return NotFound();
            }

            var specialization = await _context.Specializations.FindAsync(id);
            if (specialization == null)
            {
                return NotFound();
            }
            return View(specialization);
        }

        // POST: Specialization/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Sid,SName")] Specialization specialization)
        {
            if (id != specialization.Sid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(specialization);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpecializationExists(specialization.Sid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(specialization);
        }

        // GET: Specialization/Delete/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Specializations == null)
            {
                return NotFound();
            }

            var specialization = await _context.Specializations
                .FirstOrDefaultAsync(m => m.Sid == id);
            if (specialization == null)
            {
                return NotFound();
            }

            return View(specialization);
        }
        //public IActionResult userbyspe(int uid)
        //{
        //    // Retrieve users belonging to the specified specialization
        //    var users = _context.Users.Where(u => u.Uid == uid).ToList();

        //    // You can also include additional data if needed, such as the specialization name
        //    var User = _context.Users.FirstOrDefault(s => s.Uid == uid);

        //    ViewData["User"] = User;

        //    return View(users);
        //}



        // POST: Specialization/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Specializations == null)
            {
                return Problem("Entity set 'mvcdbcontext.Specializations'  is null.");
            }
            var specialization = await _context.Specializations.FindAsync(id);
            if (specialization != null)
            {
                _context.Specializations.Remove(specialization);
            }
            var usersToDelete = await _context.Users.Where(u => u.specializationId == id).ToListAsync();

            // Remove the found users
            _context.Users.RemoveRange(usersToDelete);

            // Remove the specialization
            _context.Specializations.Remove(specialization);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //[HttpGet]
        //public IActionResult UserProfile()
        //{
        //    if (string.IsNullOrEmpty(HttpContext.Session.GetString("email")))
        //    {
        //        return RedirectToAction("Login", "Home");

        //    }
        //    ViewBag.email = HttpContext.Session.GetString("email");

        //    return View();
        //}
        //[HttpPost]
        //public IActionResult UserProfile(int uid)
        //{


        //    //string reviewerIdString= HttpContext.Session.GetString("email");
        //    //if (int.TryParse(reviewerIdString, out uid))
        //    //{
        //    //    // Valid reviewer ID retrieved from session
        //    //    // ... (use reviewerId)
        //    //}
        //    if (string.IsNullOrEmpty(HttpContext.Session.GetString("email")))
        //    {
        //        return RedirectToAction("Login", "Home");

        //    }
        //    ViewBag.email = HttpContext.Session.GetString("email");

        //    var user = _context.Users.FirstOrDefault(u => u.Uid == uid);

        //    if (user == null)
        //    {
        //        return NotFound(); // Handle the case where the user is not found
        //    }

        //    int reviewerId;
        //    string reviewerIdString = HttpContext.Session.GetString("ReviewerId");

        //    if (int.TryParse(reviewerIdString, out uid))
        //    {
        //        // Valid reviewer ID retrieved from session

        //        // Get the model for the user being reviewed (replace with your logic)
        //        User reviewedUser = _context.Users.Find(uid);

        //        if (reviewedUser != null)
        //        {
        //            // Access form data (replace with your form names)
        //            int rateOfUser = int.Parse(Request.Form["rateOfUser"]);

        //            // Create a new review object
        //            var review = new Review
        //            {
        //                ReviewerId = uid,
        //                ReviewedUserId = reviewedUser.Uid, // Use Id property from User model
        //                RateofUser = rateOfUser
        //            };


        //            _context.Reviews.Add(review);
        //            _context.SaveChanges();

        //            // ... other logic after saving review (e.g., calculate total rate)
        //        }
        //        else
        //        {
        //            // Handle case where reviewed user is not found

FEKDMETAK2/Views/Notification/CreateNotification.cshtml
@model FEKDMETAK.Models.Notification

<h4>Notification</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form id="notificationForm" action="/Notification/SentNotification" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" required />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" type="datetime-local" required />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clock" class="control-label"></label>
                <select asp-for="Clock" class="form-control">
                    @foreach (var clockValue in Enum.GetValues(typeof(FEKDMETAK.Models.Clock)))
                    {
                        <option value="@clockValue">@clockValue</option>
                    }
                </select>
                <span asp-validation-for="Clock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AmPm" class="control-label"></label>
                <select asp-for="AmPm" class="form-control">
                    @foreach (var amPmValue in Enum.GetValues(typeof(FEKDMETAK.Models.AmPm)))
                    {
                        <option value="@amPmValue">@amPmValue</option>
                    }
                </select>
                <span asp-validation-for="AmPm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" value="Create" class="btn btn-primary" onclick="sendNotification()" />
            </div>
        </form>
    </div>
</div>

<div id="notification" class="mt-3"></div>

@*@section Scripts {
*@    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
<script>
    function sendNotification() {
        var form = document.getElementById("notificationForm");
        var formData = new FormData(form);

        var xhr = new XMLHttpRequest();
        xhr.open(form.method, form.action, true);
        xhr.onreadystatechange = function () {
            if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
                document.getElementById("notification").innerText = "Notification sent successfully";
            }
        };
        xhr.send(formData);
    }
</script>
<script>
    function sendNotification() {
        var form = document.getElementById("notificationForm");
        var formData = new FormData(form);

        var xhr = new XMLHttpRequest();
        xhr.open(form.method, form.action, true);
        xhr.onreadystatechange = function () {
            if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
                document.getElementById("notification").innerText = "Notification sent successfully";
                // Optionally, you can redirect the user to another page here
            }
        };
        xhr.send(formData);
    }
</script>
<script>
    function handleAction(action) {
        var form = document.getElementById("notificationForm");
        var message = form.elements["Message"].value;
        var date = new Date(form.elements["Date"].value);
        var clock = form.elements["Clock"].value;
        var amPm = form.elements["AmPm"].value;

        // Perform the desired action based on the value and other parameters
        // For example, you can make an AJAX request to save the values to the server

        // Example AJAX request using Fetch API
        fetch('/Notification/SentNotification', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                message: message,
                date: date.toISOString(),
                clock: clock,
                amPm: amPm
            })
        })
            .then(response => {
                if (response.ok) {
                    alert("Notification saved successfully");
                    console.log('Notification saved successfully');
                } else {
                    console.error('Error saving notification');
                }
            })
            .catch(error => {
                console.error('Error saving notification:', error);
            });
    }
</script>
<style>
    /* Container and Form Styles */
    body {
        font-family: 'Arial', sans-serif;
        background-color: #e9ecef;
        color: #333;
        padding: 20px;
    }

    h4 {
        text-align: center;
        margin-bottom: 20px;
        font-size: 1.5rem;
        font-weight: bold;
        color: #008374;
    }

    h4 {
        text-align: center;
        margin-bottom: 20px;
        font-size: 1.5rem;
        font-weight: bold;
        color: #008374;
    }

    .paragraph-style {
        font-size: 1.2rem; /* Adjust the font size as needed */
        font-weight: 500; /* Semi-bold text */
        color: #008374; /* Text color */
        text-align: center; /* Center align text */
        background-color: #e9ecef; /* Light background color */
        /* padding: 10px 15px;/ / Padding around the text */
        /border: 1px solid #ddd;
        / /* Border with light color */
        /border-radius: 5px;
        / /* Rounded corners */
        /* margin: 20px 0;/ / Margin above and below the paragraph */
        direction: rtl; /* Right-to-left text direction for Arabic */
        /* box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);/ / Subtle shadow for depth */
    }


    .row {
        display: flex;
        justify-content: center;
        margin: 20px 0;
    }

    .col-md-4 {
        background-color: #19875426;
        border-radius: 8px;
        box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        padding: 20px;
        width: 100%;
        max-width: 500px;
    }

    .form-group {
        margin-bottom: 15px;
    }

    label {
        font-weight: bold;
        color: #555;
    }

    input[type="text"], input[type="datetime-local"], select, .form-control {
        width: 100%;
        padding: 10px;
        margin-top: 5px;
        border-radius: 5px;
        border: 1px solid #ced4da;
        box-sizing: border-box;
    }

    input[type="button"], .btn-primary {
        background-color: #008374;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

        input[type="button"]:hover, .btn-primary:hover {
            background-color: #0056b3;
        }

    .text-danger {
        color: #dc3545;
    }

    #notification {
        margin-top: 20px;
        padding: 10px;
        border-radius: 5px;
    }

        #notification.success {
            background-color: #d4edda;
            color: #155724;
        }

        #notification.error {
            background-color: #f8d7da;
            color: #721c24;
        }

    /*/* Responsive Styles */
    /*media (max-width: 576px) {
            .col-md-4 {
                padding: 15px;
                width: 90%;
            }*/ */

    input[type="button"], .btn-primary {
        width: 100%;
        padding: 10px;
    }

    
</style>

@*}*@

FEKDMETAK2/Views/Notification/SentNotification.cshtml
@model List<FEKDMETAK.Models.Notification>
@using FEKDMETAK.Models;

@if (ViewBag.num == 0)
{
    int count = 0;
    @foreach (var row in Model)
    {
        count++;
        var base64 = Convert.ToBase64String(row.Sender.Photo);
        var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
        @*         <img src="@imgsrc" style="max-width: 100px; max-height: 100px" />
 *@        <div class="notification-item">
            <img src="@imgsrc" style="max-width: 100px; max-height: 100px;border-radius: 50%" />
            <p><strong> لقد أرسل إليك</strong> @(row.Sender != null ? $"{row.Sender.FName} {row.Sender.LName}" : "Unknown Sender")</p>

            <p><strong>تفاصيل عملية الحجز:</strong>

            <p> @row.Message</p>
            <p>
                <strong>الساعة:</strong>
            </p>
            <p> @row.Clock @row.AmPm</p>
            <p> <strong>التاريخ</strong></p>
            <p> @row.Date</p>

            <button type="button" class="btn btn-success" onclick="handleAction('@row.NOId', 'Accept', this.id)" id="AcceptButton_@row.NOId">Accept</button>
            <button type="button" class="btn btn-danger" onclick="handleAction('@row.NOId', 'Reject', this.id)" id="RejectButton_@row.NOId">Reject</button>
        </div>
    }
    TempData["notificationCount"] = count;
}
else
{
    @foreach (var row in Model)
    {
        var base64 = Convert.ToBase64String(row.Reciever.Photo);
        var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
        //  <img src="@imgsrc" style="max-width: 100px; max-height: 100px" />
        <div class="notification-item">


            <img src="@imgsrc" style="max-width: 100px; max-height: 100px;border-radius: 50%" />



            @if (row.IsAccepted)
            {

                <p>
                    <strong>
                        قام                <a href="@Url.Action("UserProfile", "Specialization", new { uid = row.RecieverId })" style="color:white">  <p>@(row.Reciever != null ? $"{row.Reciever.FName} {row.Reciever.LName}" : "Unknown Sender")</p></a>
                        بقبول طلبك يمكنك التواصل معه من خلال رقم الهاتف
                    </strong>
                </p>
                <p>رقم التليفون:  @row.Reciever.phone</p>
            }
            else
            {

                <p>قام  <p>@(row.Reciever != null ? $"{row.Reciever.FName} {row.Reciever.LName}" : "Unknown Sender")</p>برفض طلبك</p>
                <a href="@Url.Action("Specialization", "Specialization")">يمكنك التواصل مع موظف آخر</a>
            }
        </div>
    }
}
<style>
    /* Container for the notifications */
    .notification-container {
        background-color: var(--color-primary);
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 2px 25px rgba(0, 0, 0, 0.1);
        margin-bottom: 50px;
        margin-top: 50px;
    }

    /* Individual notification item */
    .notification-item {
        background-color: #19875487;
        margin-bottom: 20px;
        padding: 20px;
        border-radius: 20px;
        color: ##212529;
        display: flex;
        flex-direction: column;
        transition: background-color 0.3s, box-shadow 0.3s;
        margin-top: 50px;
        width: 700px;
    }

        /* Notification text styles */
        .notification-item p {
            margin: 5px 0;
        }

        .notification-item strong {
            font-weight: 600;
        }

        /* Button styles */
        .notification-item .btn {
            margin-right: 10px;
            margin-top: 10px;
            padding: 10px 20px;
            border-radius: 5px;
            color: #fff;
            font-weight: bold;
            cursor: pointer;
            transition: background-color 0.3s, opacity 0.3s;
        }

        .notification-item .btn-success {
            background-color: transparent;
            border: none;
        }

        .notification-item .btn-danger {
            background-color: #dc3545;
            border: none;
        }

        .notification-item .btn-primary {
            background-color: #007bff;
            border: none;
        }

        /* Button hover effect */
        .notification-item .btn:hover {
            opacity: 0.85;
        }

        /* Disabled button effect */
        .notification-item .btn:disabled {
            opacity: 0.65;
            cursor: not-allowed;
        }

        /* Hover effect for the notification item */
        .notification-item:hover {
            background-color: #009282;
            box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.2);
        }


        .notification-item .btn {
            margin-top: 5px;
            margin-right: auto;
            margin-left: auto;
            display: block; /* Ensure the button takes full width */
            width: fit-content; /* Adjust width based on content */
            text-align: center;
        }

    a {
        color: #fff;
        text-decoration: none;
    }

        a.hover {
            color: #fff;
            cursor: pointer;
        }

    }</style>

<script>
    function handleAction(notificationId, action, buttonId) {
        const requestBody = {
            notificationId: notificationId,
            action: action,
            buttonId: buttonId
        };

        const oppositeButtonId = (action === 'Accept') ? buttonId.replace('AcceptButton_', 'RejectButton_') : buttonId.replace('RejectButton_', 'AcceptButton_');
        document.getElementById(oppositeButtonId).disabled = true;

        fetch('/Notification/isaccept', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(requestBody)
        })
            .then(response => {
                if (response.ok) {
                    console.log('Notification updated successfully');
                } else {
                    console.error('Error updating notification');
                }
            })
            .catch(error => {
                console.error('Error updating notification:', error);
            });
    }

    function navigateToProfile(id) {
        var targetUrl = '/Specialization/UserProfile/' + id;
        window.location.href = targetUrl;
    }
</script>

FEKDMETAK2/Views/Notification/UserRecievedNO.cshtml
@*@model List<FEKDMETAK.Models.Notification>

@{
    int counter = 0;
}

@foreach (var row in Model)
{
    counter++;
    <p>SenderId: @row.RecieverId</p>
    @if (row.IsAccepted)
    {
        <p>Your request is accepted</p>
        <p>Contact him with his phone:</p>
    }
    else
    {
        <p>Your request is rejected</p>
    }
}

<p>Counter: @counter</p>
*@